from xml.dom.minidom import parseString;
import area as a;
#import argparse;


def np_toStr(fArr) :
	ret = "";
	for i in fArr:
		ret += repr(i) + " ";
	return ret;



myLand = a.make_ten();
print myLand;
pos_trans ="""
		<CondProb>
			<Var>Pc_now</Var>
			<Parent>Pc_prev</Parent>
			<Parameter type = "TBL">
"""
for i in range(myLand.xdim):
	for j in range(myLand.ydim):
		myLand[i,j];
		for dirn in a.validDirs:
			adj = myLand.get_neighbour(i, j, dirn);
			if(myLand.is_outside(adj[0],adj[1]) == False):
				pos_trans += """
				<Entry>
				<Instance>"""+"Pc"+repr(adj[0])+repr(adj[1])+" Pc"+repr(i)+repr(j)+""" </Instance> 
				<ProbTable>""" + repr(myLand[i,j].pr[dirn]) + """</ProbTable>
				</Entry>
				"""
pos_trans += """</Parameter>
				</CondProb>""";
		


doc = parseString("""<?xml version="1.0" ?><pomdpx id="autogenerated" version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pomdpx.xsd">


<Description>This is an auto-generated POMDPX file</Description>
<Discount>0.95</Discount>		  

<Variable>

<StateVar fullyObs="true" vnameCurr="x_1" vnamePrev="x_0">
	<NumValues>100</NumValues>
</StateVar>

<StateVar fullyObs="true" vnameCurr="gps_1" vnamePrev="gps_0">
<ValueEnum>ON OFF</ValueEnum>
</StateVar>

<ActionVar vname="action_agent">
<ValueEnum>a-ON a-OFF</ValueEnum>
</ActionVar>
<RewardVar vname="reward_agent"/>
</Variable>

<InitialStateBelief>
<CondProb>
 <Var>x_0</Var>
 <Parent>null</Parent>
 <Parameter type = "TBL"> 
	 <Entry>
		 <Instance> - </Instance>
		 <ProbTable>uniform</ProbTable>
	</Entry>
</Parameter>
</CondProb>
<CondProb>
 <Var>y_0</Var>
 <Parent>null</Parent>
 <Parameter type = "TBL"> 
	 <Entry>
		 <Instance> - </Instance>
		 <ProbTable>uniform</ProbTable>
	</Entry>
</Parameter>
</CondProb>
<CondProb>
 <Var>gps_0</Var>
 <Parent>null</Parent>
 <Parameter type = "TBL"> 
	 <Entry>
		 <Instance> - </Instance>
		 <ProbTable> 0 1 </ProbTable>
	</Entry>
</Parameter>
</CondProb>
</InitialStateBelief>

<StateTransitionFunction>
""" +
      pos_trans + """
      <CondProb>
          <Var>gps_1</Var>
          <Parent>action_agent gps_0 </Parent>
          <Parameter type = "TBL">
              <Entry>
                   <Instance>a-ON ON ON</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a-ON OFF ON</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a-OFF OFF OFF</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a-OFF ON OFF</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
          </Parameter>
      </CondProb>
 </StateTransitionFunction>

 <RewardFunction>
  
  <Func>
  <Var>reward_agent</Var>
  <Parent>action_agent </Parent>
  <Parameter type="TBL">
  <Entry>
  <Instance>a-ON  </Instance>
  <ValueTable> 1.0 </ValueTable></Entry>
  <Entry>
  <Instance>a-OFF  </Instance>
  <ValueTable> 0.0 </ValueTable></Entry>
  </Parameter>
  </Func>
  </RewardFunction></pomdpx>

	"""	);
with open("ff_pos10.pomdpx", "w") as f:
	f.write( doc.toxml() );
quit();
