from xml.dom.minidom import parseString;
import numpy as np;
import area as a;
#import argparse;

def np_toStr(fArr) :
	ret = "";
	for i in fArr:
		ret += repr(i) + " ";
	return ret;
myLand = a.make_ten();
print myLand;
xtrans = "";
for i in range(10):
	for j in range(10):
		myLand[i,j];
		x_trans += """<Entry>
		<Instance>""" + "s" + repr(i) + " s" + repr(j) + " s" + repr(i) + """</Instance>
		<ProbTable>""" + repr(myLand[i,j].pr['p0']) + """</ProbTable>
		</Entry>""";
		if(i > 0): # IF not west edge, define transition to west
			x_trans += """<Entry>
			<Instance>""" + "s" + repr(i) + " s" + repr(j) + " s" + repr(i-1) + """</Instance>
			<ProbTable>""" + repr(myLand[i,j].pr['pw']) + """</ProbTable>
			</Entry>
			""";  
		if(i < 9): # IF not east edge, define transition to east
			x_trans += """<Entry>
			<Instance>""" + "s" + repr(i) + " s" + repr(j) + " s" + repr(i+1) + """</Instance>
			<ProbTable>""" + repr(myLand[i,j].pr['pe']) + """</ProbTable>
			</Entry>
			""";  
		
y_trans = "";
for i in range(10):
	for j in range(10):
		myLand[i,j]; #transition to same pos
		y_trans += """<Entry>
		<Instance>""" + "s" + repr(i) + " s" + repr(j) + " s" + repr(j) + """</Instance>
		<ProbTable>""" + repr(myLand[i,j].pr['p0']) + """</ProbTable>
		</Entry>
		""";
		if(j > 0): # IF not south edge, define transition to south
			x_trans += """<Entry>
			<Instance>""" + "s" + repr(i) + " s" + repr(j) + " s" + repr(j-1) + """</Instance>
			<ProbTable>""" + repr(myLand[i,j].pr['ps']) + """</ProbTable>
			</Entry>
			""";  
		if(j < 9): # IF not north edge, define transition to north 
			x_trans += """<Entry>
			<Instance>""" + "s" + repr(i) + " s" + repr(j) + " s" + repr(j+1) + """</Instance>
			<ProbTable>""" + repr(myLand[i,j].pr['pn']) + """</ProbTable>
			</Entry>
			""";  

doc = parseString("""<?xml version="1.0" ?><pomdpx id="autogenerated" version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pomdpx.xsd">


<Description>This is an auto-generated POMDPX file</Description>
<Discount>0.95</Discount>		  

<Variable>

<StateVar fullyObs="true" vnameCurr="x_1" vnamePrev="x_0">
	<NumValues>10</NumValues>
</StateVar>
<StateVar fullyObs="true" vnameCurr="y_1" vnamePrev="y_0">
	<NumValues>10</NumValues>
</StateVar>
	<StateVar fullyObs="true" vnameCurr="gps_1" vnamePrev="gps_0">
<ValueEnum>ON OFF</ValueEnum>
</StateVar>

<ActionVar vname="action_agent">
<ValueEnum>a-ON a-OFF</ValueEnum>
</ActionVar>
<RewardVar vname="reward_agent"/>
</Variable>

<InitialStateBelief>
<CondProb>
 <Var>x_0</Var>
 <Parent>null</Parent>
 <Parameter type = "TBL"> 
	 <Entry>
		 <Instance> - </Instance>
		 <ProbTable>uniform</ProbTable>
	</Entry>
</Parameter>
</CondProb>
<CondProb>
 <Var>y_0</Var>
 <Parent>null</Parent>
 <Parameter type = "TBL"> 
	 <Entry>
		 <Instance> - </Instance>
		 <ProbTable>uniform</ProbTable>
	</Entry>
</Parameter>
</CondProb>
<CondProb>
 <Var>gps_0</Var>
 <Parent>null</Parent>
 <Parameter type = "TBL"> 
	 <Entry>
		 <Instance> - </Instance>
		 <ProbTable> 0 1 </ProbTable>
	</Entry>
</Parameter>
</CondProb>
</InitialStateBelief>

<StateTransitionFunction>
""" + xy_trans + """
      <CondProb>
          <Var>gps_1</Var>
          <Parent>action_agent gps_0 </Parent>
          <Parameter type = "TBL">
              <Entry>
                   <Instance>a-ON ON ON</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a-ON OFF ON</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a-OFF OFF OFF</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a-OFF ON OFF</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
          </Parameter>
      </CondProb>
 </StateTransitionFunction>

 <RewardFunction>
  
  <Func>
  <Var>reward_agent</Var>
  <Parent>action_agent </Parent>
  <Parameter type="TBL">
  <Entry>
  <Instance>a-ON  </Instance>
  <ValueTable> 1.0 </ValueTable></Entry>
  <Entry>
  <Instance>a-OFF  </Instance>
  <ValueTable> 0.0 </ValueTable></Entry>
  </Parameter>
  </Func>
  </RewardFunction></pomdpx>

	"""	);
with open("ff_pos10.pomdpx", "w") as f:
	    f.write( doc.toxml() );
	    
quit();
