from xml.dom.minidom import parseString;
import area as a;
#import argparse;


def np_toStr(fArr) :
	ret = "";
	for i in fArr:
		ret += repr(i) + " ";
	return ret;

## Generate 'land' map of transition probs

myLand = a.make_ten();
print myLand;

## Write Pc stuff (mean location)
Pc_trans ="""
		<CondProb>
			<Var>Pc_now</Var>
			<Parent>Pc_prev</Parent>
			<Parameter type = "TBL">
"""
Pc_enum = "";
for i in range(myLand.xdim):
	for j in range(myLand.ydim):
		Pc_enum += " Pc"+repr(i)+"_" +repr(j) + " ";
		myLand[i,j];
		for dirn in a.validDirs:
			adj = myLand.get_neighbour(i, j, dirn);
			if(myLand.is_outside(adj[0],adj[1]) == False):
				Pc_trans += """
				<Entry>
				<Instance>"""+"Pc"+repr(i)+"_"+repr(j)+" Pc"+repr(adj[0])+"_"+repr(adj[1])+""" </Instance> 
				<ProbTable>""" + repr(myLand[i,j].pr[dirn]) + """</ProbTable>
				</Entry>
				"""
Pc_trans += """</Parameter>
				</CondProb>""";
'''
## Write Pr stuff (mean error) ########################
'''

Pr_base = 0; #lowest possible error 0 means we are 100% certain of Pc
Pr_max = 4# myLand.xdim ; #largest possible error
Pr_enum = "";

Pr_trans = """
		<CondProb>
		<Var>Pr_now</Var>
		<Parent>GPS_prev Pr_prev</Parent>
		<Parameter type = "TBL">
""";


for i in range(Pr_base, Pr_max):
	Pr_enum += " Pr" + repr(i) + " ";
	if(i > Pr_base): 
		Pr_trans += """
			<Entry>
			<Instance>LOCK """ + "Pr" + repr(i) + " Pr" + repr(i-1) + """</Instance>
			<ProbTable> 1 </ProbTable>
			</Entry>
		""";
	else: # Min error, remain stationary 
		Pr_trans += """
			<Entry>
			<Instance>LOCK """ + "Pr" + repr(i) + " Pr" + repr(i) + """</Instance>
			<ProbTable> 1 </ProbTable>
			</Entry>
		""";
	if(i < Pr_max - 1):
		Pr_trans += """
			<Entry>
			<Instance>ON """ + "Pr" + repr(i) + " Pr" + repr(i+1) + """</Instance>
			<ProbTable> 1 </ProbTable>
			</Entry>
		""";
		Pr_trans += """
			<Entry>
			<Instance>OFF """ + "Pr" + repr(i) +" Pr" + repr(i+1) + """</Instance>
			<ProbTable> 1 </ProbTable>
			</Entry>
		""";
	else: #Max error remain stationary
		Pr_trans += """
			<Entry>
			<Instance>ON """ + "Pr" + repr(i) + " Pr" + repr(i) + """</Instance>
			<ProbTable> 1 </ProbTable>
			</Entry>
		""";
		Pr_trans += """
			<Entry>
			<Instance>OFF """ + "Pr" + repr(i) +" Pr" + repr(i) + """</Instance>
			<ProbTable> 1 </ProbTable>
			</Entry>
		""";
Pr_trans += """</Parameter>
				</CondProb>""";
				
				
'''
####GPSstat stuff #####################
'''
GPSstat_enum = '';
GPSstat_trans = """
		<CondProb>
		<Var>GPSstat_now</Var>
		<Parent>GPS_prev GPSstat_prev </Parent>
		<Parameter type = "TBL">
""";
GPSstat_max = 10; # Max time we can record before GPS gets a lock
GPSstat_min = 0; # Min locking time 1 -> 1 timestep from action_on
for i in range(GPSstat_min,GPSstat_max):
	GPSstat_enum += ' GPSstat_' + repr(i) + ' ';
	if(i < GPSstat_max - 1):
		GPSstat_trans += """
				<Entry>
				<Instance>OFF """ + 'GPSstat_'+repr(i) + " GPSstat_"+repr(i+1)+"""</Instance>
				<ProbTable> 1 </ProbTable> 
				</Entry>
				"""; 
		GPSstat_trans += """
				<Entry>
				<Instance>ON """ + 'GPSstat_'+repr(i) + " GPSstat_"+repr(i+1)+"""</Instance>
				<ProbTable> 1 </ProbTable> 
				</Entry>
				"""; 
	else:
		GPSstat_trans += """
				<Entry>
				<Instance>OFF """ + 'GPSstat_'+repr(i) + " GPSstat_"+repr(i)+"""</Instance>
				<ProbTable> 1 </ProbTable> 
				</Entry>
				"""; 
		GPSstat_trans += """
				<Entry>
				<Instance>ON """ + 'GPSstat_'+repr(i) + " GPSstat_"+repr(i)+"""</Instance>
				<ProbTable> 1 </ProbTable> 
				</Entry>
				"""; 
	if(i > GPSstat_min):
		GPSstat_trans += """
				<Entry>
				<Instance>LOCK """ + ' * ' + " GPSstat_"+repr(0)+"""</Instance>
				<ProbTable> 1 </ProbTable> 
				</Entry>
				"""; 

GPSstat_trans += """</Parameter>
					</CondProb>""";
		
header = """<?xml version="1.0" ?><pomdpx id="autogenerated" version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pomdpx.xsd">


<Description>This is an auto-generated POMDPX file</Description>
<Discount>0.95</Discount>	"""


xmlStr= (header + """
	  

<Variable>

<StateVar fullyObs="true" vnameCurr="Pc_now" vnamePrev="Pc_prev">
	<ValueEnum>""" + Pc_enum +"""</ValueEnum>
</StateVar>

<StateVar fullyObs="true" vnameCurr="Pr_now" vnamePrev="Pr_prev">
	<ValueEnum>""" + Pr_enum + """ </ValueEnum>
</StateVar>

<StateVar fullyObs="true" vnameCurr="GPSstat_now" vnamePrev="GPSstat_prev">
	<ValueEnum>""" + GPSstat_enum +  """</ValueEnum>
</StateVar>


<StateVar fullyObs="true" vnameCurr="GPS_now" vnamePrev="GPS_prev">
<ValueEnum>ON OFF LOCK</ValueEnum>
</StateVar>

<ActionVar vname="action_agent">
<ValueEnum>a_ON a_OFF</ValueEnum>
</ActionVar>
<RewardVar vname="reward_agent"/>
</Variable>

<InitialStateBelief>
<CondProb>
	 <Var>Pc_prev</Var>
	 <Parent>null</Parent>
	 <Parameter type = "TBL"> 
		<Entry>
		<Instance> - </Instance>
		<ProbTable>uniform</ProbTable>
		</Entry>
	</Parameter>
</CondProb>
<CondProb>
	<Var>GPS_prev</Var>
 	<Parent>null</Parent>
 	<Parameter type = "TBL"> 
		 <Entry>
		 <Instance> - </Instance>
		 <ProbTable> 0 1 0 </ProbTable>
		</Entry>
	</Parameter>
</CondProb>
<CondProb>
	<Var>Pr_prev</Var>
	<Parent>null</Parent>
	<Parameter type = "TBL">
		<Entry>
		<Instance> - </Instance>
		<ProbTable> uniform </ProbTable>
		</Entry>
	</Parameter>	
</CondProb>
<CondProb>
	<Var>GPSstat_prev</Var>
	<Parent>null</Parent>
	<Parameter type = "TBL">
		<Entry>
		<Instance> - </Instance>
		<ProbTable> uniform </ProbTable>
		</Entry>
	</Parameter>	
</CondProb>
</InitialStateBelief>

<StateTransitionFunction>
""" + Pc_trans + """
""" + Pr_trans + """
""" + GPSstat_trans + """
      <CondProb>
          <Var>GPS_now</Var>
          <Parent>action_agent GPS_prev </Parent>
          <Parameter type = "TBL">
              <Entry>
                   <Instance>a_ON ON ON</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a_ON OFF ON</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a_OFF OFF OFF</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
                   <Instance>a_OFF ON OFF</Instance>
                   <ProbTable>1</ProbTable>
              </Entry>
              <Entry>
              		<Instance>a_ON LOCK - </Instance>
              		<ProbTable>0.5 0 0.5</ProbTable>
              </Entry>
              <Entry>
                    <Instance>a_OFF LOCK  - </Instance>
                    <ProbTable>0 1 0</ProbTable>
              </Entry>
          </Parameter>
      </CondProb>
 </StateTransitionFunction>

 <RewardFunction>
  
  <Func>
  <Var>reward_agent</Var>
  <Parent>action_agent Pr_prev</Parent>
  <Parameter type="TBL">
  <Entry>
  <Instance>a_ON Pr1 </Instance>
  <ValueTable> 1.0 </ValueTable></Entry>
  <Entry>
  <Instance>a_OFF *  </Instance>
  <ValueTable> 0.0 </ValueTable></Entry>
  </Parameter>
  </Func>
  </RewardFunction></pomdpx>

	"""	);

with open("ff_pos10.pomdpx", "w") as f:
	f.write( xmlStr );
doc = parseString(xmlStr);
quit();
